
#?Create a program that will play the “cows and bulls” game with the user. The game works like this:

#?Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
#?For every digit that the user guessed correctly in the correct place, they have a “cow”. 
#?For every digit the user guessed correctly in the wrong place is a “bull.” 
#?Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
#?Once the user guesses the correct number, the game is over. 
#?Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

#?Say the number generated by the computer is 1038. An example interaction could look like this:

  #?Welcome to the Cows and Bulls Game! 
  #?Enter a number: 
  #?>>> 1234
  #?2 cows, 0 bulls
  #?>>> 1256
  #?1 cow, 1 bull
  #?...
#?Until the user guesses the number.

import random

#creating function to the 'cows and bulls game'
def askUser():
    return input("Give me a number with 4 digits or exit to stop: ")

def validateNumbers(userN, randN):
    cows = 0
    bulls = 0
    for x in range(0,len(randN)):
        if userN[x] == randN[x]:
            cows += 1
        elif userN[x] in randN:
            bulls += 1
    print('{}: {} cows, {} bulls'.format(userN,cows,bulls))
        

#ensure that functions will be just only imported and not automatically executed if I reuse this method by import ...
if __name__=="__main__":
    randomNumber = random.randint(1000,9999)
    while(True):
        user_num = askUser()
        if user_num == 'exit':
            break
        elif int(user_num) == randomNumber:
            print('Congratulations! \nYou guessed the right number!\n{} 4 cows, 0 bulls\nGAME OVER'.format(randomNumber))
            break
        else:
            validateNumbers(user_num,str(randomNumber))


  
